name: my-first-workflow
on : push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Check if Docker is available and install if needed
          run: |
            if ! command -v docker &> /dev/null; then
            echo "Docker not found, installing..."
            
            else
            echo "Docker is available, proceeding with the build."
           
            fi

      # Step 2: Verify Docker installation
        - name: Verify Docker installation
          run: docker --version
          
