name: my-first-workflow
on : push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: Multi stage pipeline
          run: |
              echo "my first workflow"
              ls
              cat README.md
        - name : Third-party-pipeline
          run: cowsay -f "This is a cow" >> sample.txt